version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
