version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
  disable:
    - errcheck

linters-settings:
  govet:
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-use-default: true
