package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// status values surfaced in the checklist.
const (
	statusTodo        = "TODO"        // extract only, not yet diffed
	statusImplemented = "IMPLEMENTED" // chi route matches a spec operation
	statusMissing     = "MISSING"     // spec operation has no chi route
	statusExtra       = "EXTRA"       // chi route in scope but no spec match
)

// checklist is the canonical machine-readable representation. It is
// serialized 1:1 to JSON and rendered to Markdown for human review. The
// markdown form is committed alongside the JSON so PR diffs are readable.
type checklist struct {
	Service     string             `json:"service"`
	DisplayName string             `json:"displayName,omitempty"`
	RPNamespace string             `json:"rpNamespace,omitempty"`
	GeneratedAt string             `json:"generatedAt"`
	Summary     *checklistSummary  `json:"summary,omitempty"`
	Sections    []checklistSection `json:"sections"`
}

type checklistSummary struct {
	SpecOperations    int `json:"specOperations"`
	Implemented       int `json:"implemented"`
	Missing           int `json:"missing"`
	Extra             int `json:"extra"`
	CoveragePercent   int `json:"coveragePercent"`
}

type checklistSection struct {
	Name               string           `json:"name"`
	Plane              string           `json:"plane"`
	Description        string           `json:"description,omitempty"`
	URL                string           `json:"url"`
	MinibluePathPrefix string           `json:"minibluePathPrefix,omitempty"`
	Entries            []checklistEntry `json:"entries"`
	// ExtraRoutes lists chi routes that fall in this service's scope but
	// match no spec operation. Populated only by `specport diff`.
	ExtraRoutes []extraRoute `json:"extraRoutes,omitempty"`
}

type checklistEntry struct {
	Method       string `json:"method"`
	SpecPath     string `json:"specPath"`
	MinibluePath string `json:"minibluePath"`
	OperationID  string `json:"operationId"`
	LRO          bool   `json:"lro,omitempty"`
	Pageable     bool   `json:"pageable,omitempty"`
	Summary      string `json:"summary,omitempty"`
	Status       string `json:"status"`
	// MatchedRoute is the chi pattern this entry was matched against
	// (only set when Status == IMPLEMENTED).
	MatchedRoute string `json:"matchedRoute,omitempty"`
}

type extraRoute struct {
	Method  string `json:"method"`
	Pattern string `json:"pattern"`
}

func writeChecklist(outDir string, cl *checklist) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	cl.recomputeSummary()

	jsonPath := filepath.Join(outDir, cl.Service+".json")
	if err := writeJSON(jsonPath, cl); err != nil {
		return err
	}
	mdPath := filepath.Join(outDir, cl.Service+".md")
	if err := os.WriteFile(mdPath, []byte(renderMarkdown(cl)), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", jsonPath)
	fmt.Printf("wrote %s\n", mdPath)
	if cl.Summary != nil {
		fmt.Printf("summary: implemented=%d missing=%d extra=%d coverage=%d%%\n",
			cl.Summary.Implemented, cl.Summary.Missing, cl.Summary.Extra, cl.Summary.CoveragePercent)
	}
	return nil
}

func (cl *checklist) recomputeSummary() {
	s := &checklistSummary{}
	for _, sec := range cl.Sections {
		s.SpecOperations += len(sec.Entries)
		for _, e := range sec.Entries {
			switch e.Status {
			case statusImplemented:
				s.Implemented++
			case statusMissing:
				s.Missing++
			case statusExtra:
				s.Extra++
			}
		}
		s.Extra += len(sec.ExtraRoutes)
	}
	if s.SpecOperations > 0 {
		s.CoveragePercent = (100 * s.Implemented) / s.SpecOperations
	}
	cl.Summary = s
}

func writeJSON(path string, v interface{}) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return err
	}
	return nil
}

func renderMarkdown(cl *checklist) string {
	var b strings.Builder
	heading := cl.DisplayName
	if heading == "" {
		heading = cl.Service
	}
	fmt.Fprintf(&b, "# %s — Azure spec coverage\n\n", heading)
	fmt.Fprintf(&b, "Generated by `go run ./tools/specport` at %s.\n\n",
		formatGeneratedAt(cl.GeneratedAt))
	fmt.Fprintf(&b, "Run `go run ./tools/specport extract %s` to refresh from Azure's spec.\n", cl.Service)
	fmt.Fprintf(&b, "Run `go run ./tools/specport diff %s` to update IMPLEMENTED / MISSING / EXTRA from the running miniblue router.\n\n",
		cl.Service)

	if cl.RPNamespace != "" {
		fmt.Fprintf(&b, "**Resource Provider Namespace**: `%s`\n\n", cl.RPNamespace)
	}

	if cl.Summary != nil {
		fmt.Fprintf(&b, "## Summary\n\n")
		fmt.Fprintf(&b, "| Metric | Count |\n|---|---|\n")
		fmt.Fprintf(&b, "| Spec operations | %d |\n", cl.Summary.SpecOperations)
		fmt.Fprintf(&b, "| Implemented in miniblue | %d |\n", cl.Summary.Implemented)
		fmt.Fprintf(&b, "| Missing in miniblue | %d |\n", cl.Summary.Missing)
		fmt.Fprintf(&b, "| Extra in miniblue (not in spec) | %d |\n", cl.Summary.Extra)
		fmt.Fprintf(&b, "| Coverage | %d%% |\n\n", cl.Summary.CoveragePercent)
	}

	for _, sec := range cl.Sections {
		fmt.Fprintf(&b, "## Source: %s (%s)\n\n", sec.Name, sec.Plane)
		if sec.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", sec.Description)
		}
		fmt.Fprintf(&b, "Spec: <%s>\n\n", sec.URL)
		if sec.MinibluePathPrefix != "" {
			fmt.Fprintf(&b, "Miniblue path prefix: `%s`\n\n", sec.MinibluePathPrefix)
		}
		fmt.Fprintf(&b, "| Status | Method | OperationID | Path (in miniblue) | LRO |\n")
		fmt.Fprintf(&b, "|---|---|---|---|---|\n")
		for _, e := range sec.Entries {
			lro := ""
			if e.LRO {
				lro = "yes"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | `%s` | %s |\n",
				statusBadge(e.Status), e.Method, e.OperationID, e.MinibluePath, lro)
		}
		fmt.Fprintln(&b)

		if len(sec.ExtraRoutes) > 0 {
			fmt.Fprintf(&b, "### Extra routes (in miniblue, no matching spec operation)\n\n")
			fmt.Fprintf(&b, "| Method | Pattern |\n|---|---|\n")
			for _, r := range sec.ExtraRoutes {
				fmt.Fprintf(&b, "| %s | `%s` |\n", r.Method, r.Pattern)
			}
			fmt.Fprintln(&b)
		}
	}
	return b.String()
}

func statusBadge(s string) string {
	switch s {
	case statusImplemented:
		return "**" + s + "**"
	case statusMissing:
		return "_" + s + "_"
	default:
		return s
	}
}

func formatGeneratedAt(s string) string {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return s
	}
	return t.Format("2006-01-02 15:04 UTC")
}
